### ISSUE TITLE
RegisterInstancesWithLoadBalancer fails with an underscore exception

### ISSUE THREAD

**Issue by c4milo** [chilts/awssum#61]
I'm not sure if I'm preparing correctly the parameter object, this is what I'm doing: 

``` javascript
#!/usr/bin/env node

var program = require('commander');
var awssum = require('awssum');
var amazon = awssum.load('amazon/amazon');
var Elb = awssum.load('amazon/elb').Elb;

var accessKeyId     = "";
var secretAccessKey = "";
var awsAccountId    = "";

var elb = new Elb({
  'accessKeyId'     : accessKeyId,
  'secretAccessKey' : secretAccessKey,
  'awsAccountId'    : awsAccountId, // optional
  'region'          : amazon.US_EAST_1
});

program
  .command('connect <instance_id> <lb_name>')
  .description('Connect an EC2 instance to an Elastic Load Balancer')
  .action(function(instanceId, lbname) {
    var params = {
      LoadBalancerName: lbname,
      Instances: [instanceId]
    };

    /**Note
     * Completion of this API does not guarantee that
     * operation has completed. Rather, it means that
     * the request has been registered and the changes
     * will happen shortly.
     * See: http://docs.amazonwebservices.com/ElasticLoadBalancing/latest/APIReference/API_RegisterInstancesWithLoadBalancer.html
     *
     */
    elb.RegisterInstancesWithLoadBalancer(params, function(err, data) {
      console.log(err.Body.ErrorResponse);
      //if (err) throw err;
      console.log(data);
    });
  });

program
  .command('disconnect <instance_id> <lb_name>')
  .description('Disconnect an EC2 instance from an Elastic Load Balancer')
  .action(function(instanceId, lbname) {
    var params = {
      LoadBalancerName: lbname,
      Instances: [instanceId]
    };

    elb.DeregisterInstancesFromLoadBalancer(params, function(err, data) {
      if (err) throw err;
      console.log(data);
    });
  });

program.parse(process.argv);
```

**Comment by c4milo** [comment]
btw, the error is this: 

``` shell
/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/node_modules/underscore/underscore.js:79
        if (i in obj && iterator.call(context, obj[i], i, obj) === breaker) re
                 ^
TypeError: Cannot use 'in' operator to search for '0' in i-5f781343
    at Number.IN (native)
    at Function.<anonymous> (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/node_modules/underscore/underscore.js:79:18)
    at /Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/lib/awssum.js:183:11
    at Array.forEach (native)
    at Function.<anonymous> (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/node_modules/underscore/underscore.js:76:11)
    at addParamArrayOfObjects (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/lib/awssum.js:177:7)
    at [object Object].send (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/lib/awssum.js:515:13)
    at [object Object].RegisterInstancesWithLoadBalancer (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/awssum/lib/awssum.js:349:14)
    at Command.<anonymous> (/Users/camilo/Dropbox/Development/onswipe/goblin/scripts/elb.js:36:9)
    at Command.<anonymous> (/Users/camilo/Dropbox/Development/onswipe/goblin/node_modules/commander/lib/commander.js:231:8)
```

**Comment by chilts** [comment]
Can you try it with:

```
var params = {
    LoadBalancerName: lbname,
    Instances: [
        { InstanceId : instanceId }
    ]
};
```

Cheers,
Andy

P.S. Sorry, I'm in the process of adding a lot of examples to a new docs site. Mind if I use the output of this conversation as an example in it? Preview (very alpha) here: http://awssum.appsattic.com/

**Comment by c4milo** [comment]
boom!, that did it @chilts. I would never had a commercial support like that with Oracle or Microsoft. You answered in 5 minutes! Go ahead about using the script as an example man.

**Comment by chilts** [comment]
Hi Camilo,

Sorry it wasn't clear beforehand. That's the first case I've seen at AWS where they require a complex data structure which only has one member!!! A bit of a pain, but am glad it worked.

By the way, I'm also looking for testimonials from companies using AwsSum in production which I'd like to put on the new docs site. Are you guys using it in prod yet and would you be happy if I got a quote or two off you. If you want to reply to my email, go ahead : chilts@appsattic.com

Many thanks for your help,
Andy

**Comment by c4milo** [comment]
we haven't start to use it in production yet. But if I can get this script to work reliably, we would certainly have it in production soon.

**Comment by c4milo** [comment]
btw, this is the final version of the script https://gist.github.com/3442684 It seems to be working pretty well now.

**Comment by chilts** [comment]
Crapsicle. I put the wrong issue number in on an unrelated commit. Please ignore the above commit, this issue was closed anyway. :) Oopse.
