### ISSUE TITLE
Ec2.CreateImage() - callback is not a function, huh?

### ISSUE THREAD

**Issue by techtribe** [chilts/awssum#62]
Found an error while executing CreateImage, here is your request (awssum.js debug = true ;))

---

awssum.js:request(): reqOptions =  { method: 'GET',
  host: 'ec2.eu-west-1.amazonaws.com',
  path: '/?Action=CreateImage&InstanceId=i-0fb3bc47&Name=API_0.8.7&Description=Made%20a%20snapshot%20from%20a%20launched%20instance%20for%20EC2%20run%20actions.&AWSAccessKeyId=.............................&SignatureVersion=2&SignatureMethod=HmacSHA256&Timestamp=2012-08-24T08%3A39%3A45.797Z&Version=2012-04-01&Signature=OyUdDa%2BOFzDUqHXop6iSlCzLmoMuFNsJg0rHztXtsMw%3D',
  headers: { 'User-Agent': 'awssum/0.8.0' } }
awssum.js:request(): body       =  undefined
create tags: { ResourceId: [ 'i-0fb3bc47' ],
##   Tag: [ { Key: 'AMI', Value: 'SNAPSHOT' } ] }

---

Response:
- statusCode : 200
- headers : { 'content-type': 'text/xml;charset=UTF-8',
  'transfer-encoding': 'chunked',
  date: 'Fri, 24 Aug 2012 08:39:45 GMT',
  server: 'AmazonEC2' }
- body : <?xml version="1.0" encoding="UTF-8"?>
  <CreateImageResponse xmlns="http://ec2.amazonaws.com/doc/2012-04-01/">
  <requestId>885695c2-2269-4025-8b4e-f1d2ff839459</requestId>
  <imageId>ami-53686e27</imageId>
  </CreateImageResponse>
  -------------------------------------------------------------------------------

and here is the error I am getting:

TypeError: object is not a function
    at AwsSum.send (/Users/joeyvandijk/work/intellij/NODEJS_OMRON_CONTROL/base/node_modules/awssum/lib/awssum.js:806:9)
    at _.once (/Users/joeyvandijk/work/intellij/NODEJS_OMRON_CONTROL/base/node_modules/underscore/underscore.js:576:26)
    at IncomingMessage.AwsSum.request (/Users/joeyvandijk/work/intellij/NODEJS_OMRON_CONTROL/base/node_modules/awssum/lib/awssum.js:880:13)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at CleartextStream.socketOnData [as ondata](http.js:1366:20)
    at CleartextStream.CryptoStream._push (tls.js:492:27)
    at SecurePair.cycle (tls.js:846:20)
    at EncryptedStream.CryptoStream.write (tls.js:227:13)

and when I output just before that line 

```
 callback(null,result);  (awssum.js line ~803)
```

i am seeing that callback is not a function but an object and therefore I am getting this error. it starts with:

```
{ ArrayBuffer: [Function: ArrayBuffer],
```

  Int8Array: { [Function: Int8Array] BYTES_PER_ELEMENT: 1 },
  Uint8Array: { [Function: Uint8Array] BYTES_PER_ELEMENT: 1 },
  Uint8ClampedArray: { [Function: Uint8ClampedArray] BYTES_PER_ELEMENT: 1 },
  Int16Array: { [Function: Int16Array] BYTES_PER_ELEMENT: 2 },
  Uint16Array: { [Function: Uint16Array] BYTES_PER_ELEMENT: 2 },
  Int32Array: { [Function: Int32Array] BYTES_PER_ELEMENT: 4 },
  Uint32Array: { [Function: Uint32Array] BYTES_PER_ELEMENT: 4 },
  Float32Array: { [Function: Float32Array] BYTES_PER_ELEMENT: 4 },
  Float64Array: { [Function: Float64Array] BYTES_PER_ELEMENT: 8 },
  DataView: [Function: DataView],
....

When I look at the documentation 

```
http://docs.amazonwebservices.com/AWSEC2/latest/APIReference/ApiReference-query-CreateImage.html
```

i am not seeing any strange code in

```
 https://github.com/appsattic/node-awssum/blob/master/lib/amazon/ec2-config.js
```

so I couldn't trace back the place of the error, but maybe you understand what goes wrong? Can you make an image from a running instance with ec2.CreateImage({InstanceId:'i-......',Name:'somename'});?

Thanks.

;)

**Comment by techtribe** [comment]
Apparantly I found the issue. I am using Step and had an group-issue that 1 call was in the group and the other not, which resulted in resetting the callback-property in awssum.js so it would send wrong requests and apparantly it resulted in a situation where callback became an object and not a function anymore.

So, for all fellow developers that think it is because of the library, this is because of YOU. ;) Watch out with Step to use group() everywhere in the same function or not at all.

FYI
